sudo: false
language: cpp
cache:
  ccache: true
  directories:
  - "/home/travis/toolchain"

matrix:
  include:

  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost1.55-all-dev
        - libssl-dev
        - g++-8
        - gcc-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="linux-gcc-8"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost1.55-all-dev
        - libssl-dev
        - g++-7
        - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="linux-gcc-7"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  - os: osx
    osx_image: xcode10
    compiler: gcc
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="osx-g++-8"
    - STRIP="strip"

  - os: osx
    osx_image: xcode10
    compiler: gcc
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="osx-g++-7"
    - STRIP="strip"

  - os: osx
    osx_image: xcode10
    compiler: clang
    env:
    - MATRIX_EVAL="CC=/usr/local/opt/llvm/bin/clang && CXX=/usr/local/opt/llvm/bin/clang++"
    - LABEL="osx"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  - os: linux
    env:
    - MATRIX_EVAL="CC=aarch64-linux-gnu-gcc && CXX=aarch64-linux-gnu-g++"
    - LABEL="aarch64"
    - _DEPLOYABLE="true"
    - STRIP="aarch64-linux-gnu-strip"

before_install:
- eval $MATRIX_EVAL

install:
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew cask uninstall --force oclint || true
  ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install llvm || travis_retry
  brew upgrade llvm ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install openssl || travis_retry
  brew upgrade openssl ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew link --force openssl ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then ln -s /usr/local/opt/openssl/include/openssl
  /usr/local/include ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install ccache ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"
  ; fi
- if [[ "$LABEL" == "osx-g++-8" ]]; then travis_retry brew install gcc@8 ; fi
- if [[ "$LABEL" == "osx-g++-7" ]]; then travis_retry brew install gcc@7 ; fi

script:
- eval $MATRIX_EVAL
- if [[ "$LABEL" == "aarch64" ]]; then source scripts/prep-aarch64.sh ; fi
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Release -DSTATIC=true ..
- make -j2
- if [[ "$LABEL" != "aarch64" ]]; then ./src/cryptotest ; fi

before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- TARGETS="kegcoind kegwallet kegwallet-beta kegcoin-service kegminer cryptotest wallet-api"
- "${STRIP} ${TARGETS}"
- rm -rf KegcoinGold-${TRAVIS_TAG}
- mkdir KegcoinGold-${TRAVIS_TAG}
- cp ${TARGETS} KegcoinGold-${TRAVIS_TAG}/
- cp ../../LICENSE KegcoinGold-${TRAVIS_TAG}/
- tar -zcvf KegcoinGold-${TRAVIS_TAG}-${LABEL}.tar.gz KegcoinGold-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp KegcoinGold-${TRAVIS_TAG}-${LABEL}.tar.gz builds

deploy:
  provider: releases
  api_key:
    secure: "T40RFyWOgL1zjShmxm5Ab/k/G/etVWy5wkqj0/4nPOY21cimVU4dbZp0tgezMQKD0lc30q2G9nxakQeCzf4aPCNhfqYmIgA3WFcMm0s59mWzaSVOUurhQRVjusVac6iNSSrDiV2ENgqyNMxKAuiULkxE+3oM0iXNFNeHl9Fkc9YXrWAPOrNZVf6JUk9dR/7qJsywqbPVS3bSmL6wq75i0ssAmKA2MmhCaRDEJJvnH4LEgLNXFJjjm/ug5DUoIf6K7mh7sQSZa863iROyfEOn69ICpLyEVmQUf76fhW1zOy8Se/rWpfPkBPhsmH32EQJu0kUZ/Slt3jK3cw81DcLV3zSdWyBdrtUTCmEaKeVENLKMpyTqMf8oflxeihCNkB4ILisWx5Bmu7SFFRi47os8wzxgQg0xg+siFbFtmFnYGxWRXf1/s7YCe+SZlEKctALar5e5Vype+tKkS64eLlevCt7w5XPmqnd9q1ek6aURaC7MP53ScLeOWcDbjIcwZLAoVpYJ+/8Qir7jN0EyhO9FZp8v7zAS14eIQqd231mkCAqIqYR/ava4jZVmU9xnvx/lAmTca2RWXIEqDt+qhyTO4s6aitBwSoWO+etBk0YzebgR6RApTwro8JTvzICU/QWhxUU1YeuU+OrmebFJYJC8SB/vczY8KutLv5oQS5Bj8Kk="
  file:
    - KegcoinGold-${TRAVIS_TAG}-${LABEL}.tar.gz
  skip_cleanup: true
  on:
    repo: kegcoin-project/kegcoin-gold
    tags: true
    condition: "$_DEPLOYABLE = true"
